src/AppBundle/Entity/Project.php
<?php

namespace AppBundle\Entity;

/**
 * Project
 */
class Project
{
    const STATUS_NEW        = 'NEW';
    const STATUS_QUEUED     = 'QUEUED';
    const STATUS_RENDERING  = 'RENDERING';
    const STATUS_PAUSED     = 'PAUSED';
    const STATUS_STOPPED    = 'STOPPED';
    const STATUS_FINISHED   = 'FINISHED';

    public static $imageFormats = array(
        'PNG' => 'png',
        'JPEG' => 'jpg'
    );

    public static $engines = array(
        'BLENDER_RENDER' => 'Blender Render',
        'CYCLES' => 'Cycles'
    );

    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $name;


    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     *
     * @return Project
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }
    /**
     * @var string
     */
    private $status;


    /**
     * Set status
     *
     * @param string $status
     *
     * @return Project
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }
    /**
     * @var integer
     */
    private $frameStart;

    /**
     * @var integer
     */
    private $frameEnd;


    /**
     * Set frameStart
     *
     * @param integer $frameStart
     *
     * @return Project
     */
    public function setFrameStart($frameStart)
    {
        $this->frameStart = $frameStart;

        return $this;
    }

    /**
     * Get frameStart
     *
     * @return integer
     */
    public function getFrameStart()
    {
        return $this->frameStart;
    }

    /**
     * Set frameEnd
     *
     * @param integer $frameEnd
     *
     * @return Project
     */
    public function setFrameEnd($frameEnd)
    {
        $this->frameEnd = $frameEnd;

        return $this;
    }

    /**
     * Get frameEnd
     *
     * @return integer
     */
    public function getFrameEnd()
    {
        return $this->frameEnd;
    }
    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $tasks;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->tasks = new \Doctrine\Common\Collections\ArrayCollection();
    }

    /**
     * Add task
     *
     * @param \AppBundle\Entity\Task $task
     *
     * @return Project
     */
    public function addTask(\AppBundle\Entity\Task $task)
    {
        $this->tasks[] = $task;

        return $this;
    }

    /**
     * Remove task
     *
     * @param \AppBundle\Entity\Task $task
     */
    public function removeTask(\AppBundle\Entity\Task $task)
    {
        $this->tasks->removeElement($task);
    }

    /**
     * Get tasks
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getTasks()
    {
        return $this->tasks;
    }
    /**
     * @var string
     */
    private $format;


    /**
     * Set format
     *
     * @param string $format
     *
     * @return Project
     */
    public function setFormat($format)
    {
        $this->format = $format;

        return $this;
    }

    /**
     * Get format
     *
     * @return string
     */
    public function getFormat()
    {
        return $this->format;
    }

    /**
     * @return array
     */
    public static function getImageFormats()
    {
        return array_keys(self::$imageFormats);
    }

    /**
     * @var string
     */
    private $engine;


    /**
     * Set engine
     *
     * @param string $engine
     *
     * @return Project
     */
    public function setEngine($engine)
    {
        $this->engine = $engine;

        return $this;
    }

    /**
     * Get engine
     *
     * @return string
     */
    public function getEngine()
    {
        return $this->engine;
    }

    /**
     * @return array
     */
    public static function getEngines()
    {
        return array_keys(self::$engines);
    }
    /**
     * @var string
     */
    private $mainFile;


    /**
     * Set mainFile
     *
     * @param string $mainFile
     *
     * @return Project
     */
    public function setMainFile($mainFile)
    {
        $this->mainFile = $mainFile;

        return $this;
    }

    /**
     * Get mainFile
     *
     * @return string
     */
    public function getMainFile()
    {
        return $this->mainFile;
    }

    /**
     * @return int
     */
    public function getRenderTime()
    {
        $runtime = 0;
        /** @var Task $task */
        foreach($this->tasks as $task) {
            $runtime += $task->getRuntime();
        }
        return $runtime;
    }

    /**
     * @return float
     */
    public function getProgress()
    {
        if($this->tasks->count() == 0) {
            return 0;
        }

        $progress = 0;
        /** @var Task $task */
        foreach($this->tasks as $task) {
            $progress += $task->getProgress();
        }
        return ($progress / $this->tasks->count());
    }

    /**
     * @return double
     */
    public function getAverageFrameRenderingTime()
    {
        $count = 0;
        $sum = 0;
        /** @var Task $task */
        foreach($this->tasks as $task) {
            if($task->getStatus() == Task::STATUS_FINISHED) {
                $count++;
                $sum += $task->getRuntime();
            }
        }

        if($count > 0) {
            return $sum / $count;
        }

        return 0;
    }
}

src/AppBundle/Resources/views/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{{ asset('bundles/app/style/screen.css') }}">

    <title>Blender Farm {% block title %}{% endblock %}</title>
</head>

<body>
{% block navigation %}
<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ path('project_index') }}">BlenderFarm</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a href="{{ path('project_index') }}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Projects <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ path('project_index') }}">List</a></li>
                        <li><a href="{{ path('project_add') }}">Add</a></li>
                    </ul>
                </li>

                {% if is_granted('ROLE_ADMIN') %}
                <li class="dropdown">
                    <a href="{{ path('user_index') }}" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Users <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="{{ path('user_index') }}">List</a></li>
                        <li><a href="{{ path('user_add') }}">Add</a></li>
                    </ul>
                </li>
                {% endif %}

            </ul>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ path('logout') }}">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</nav>
{% endblock %}

<div class="container">
{% block body %}{% endblock %}
</div>
<script src="{{ asset('bundles/app/script/main.js') }}"></script>
{% block additionalJs %}{% endblock %}
</body>
</html>

src/AppBundle/Resources/views/index.html.twig
{% extends 'AppBundle::base.html.twig' %}

src/AppBundle/Resources/views/login.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block navigation %}{% endblock %}

{% block body %}
    <form class="form-signin" method="post" action="{{ path('login_check') }}">
        <h2 class="heading">Sign in</h2>
        {% if error %}
            <p class="text-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</p>
        {% endif %}
        <label for="username" class="sr-only">Username</label>
        <input type="text" name="_username" id="username" class="form-control" placeholder="Username" value="{{ lastUsername }}" required autofocus>
        <label for="password" class="sr-only">Password</label>
        <input type="password" name="_password" id="password" class="form-control" placeholder="Password" required>
        <div class="checkbox">
            <label>
                <input type="checkbox" name="_remember_me"> Keep me logged in
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
{% endblock %}

src/AppBundle/Resources/views/project_add_edit.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}
<h1>{% if project.id > 0 %}Edit{% else %}Add{% endif %}</h1>
<form method="post" enctype="multipart/form-data">

    <div class="form-group{% if errors.name is defined %} has-error{% endif %}">
        <label for="name">Name</label>
        <input type="text" class="form-control"  name="name" id="name" value="{{ project.name }}">
        {% if errors.name is defined %}<span class="help-block">{{ errors.name.message }}</span>{% endif %}
    </div>

    <div class="form-group{% if errors.file is defined %} has-error{% endif %}">
        <label for="file">Main Blender file</label>
        <input type="file" name="file" id="file">
        {% if errors.file is defined %}<span class="help-block">{{ errors.file.message }}</span>{% endif %}
    </div>

    <div class="form-group{% if errors.frameStart is defined %} has-error{% endif %}">
        <label for="frameStart">First frame</label>
        <input type="text" class="form-control"  name="frameStart" id="frameStart" value="{{ project.frameStart }}">
        {% if errors.frameStart is defined %}<span class="help-block">{{ errors.frameStart.message }}</span>{% endif %}
    </div>

    <div class="form-group{% if errors.frameEnd is defined %} has-error{% endif %}">
        <label for="frameEnd">Last frame</label>
        <input type="text" class="form-control"  name="frameEnd" id="frameEnd" value="{{ project.frameEnd }}">
        {% if errors.frameEnd is defined %}<span class="help-block">{{ errors.frameEnd.message }}</span>{% endif %}
    </div>

    <div class="form-group{% if errors.format is defined %} has-error{% endif %}">
        <label for="format">Image format</label>
        <select name="format" class="form-control"  id="format">
            {% for key, value in imageFormats %}
                <option value="{{ key }}"{% if project.format == key %} selected{% endif %}>{{ key }} (.{{ value }})</option>
            {% endfor %}
        </select>
        {% if errors.format is defined %}<span class="help-block">{{ errors.format.message }}</span>{% endif %}
    </div>

    <div class="form-group{% if errors.engine is defined %} has-error{% endif %}">
        <label for="engine">Rendering Engine</label>
        <select name="engine" class="form-control"  id="engine">
            {% for key, value in renderingEngines %}
                <option value="{{ key }}"{% if project.engine == key %} selected{% endif %}>{{ value }}</option>
            {% endfor %}
        </select>
        {% if errors.engine is defined %}<span class="help-block">{{ errors.engine.message }}</span>{% endif %}
    </div>

    <button type="submit" class="btn btn-primary">Add</button>
    <a href="{{ path('project_index') }}" class="btn btn-default">Cancel</a>

</form>
{% endblock %}

src/AppBundle/Resources/views/project_detail.html.twig
{% extends 'AppBundle::base.html.twig' %}
{% import 'AppBundle:macros:datetime.html.twig' as datetime %}

{% block body %}
    <h1>{{ project.name }} details</h1>
    <p><a href="{{ path('project_index') }}" class="btn btn-primary">Back to overview</a></p>
    <p id="status">Status: {{ project.status }}</p>
    <p id="projectProgress">Progress: {{ (project.progress * 100)|number_format(0) }}%</p>
    <p id="renderTime">Render Time: {{ datetime.formatSeconds(project.renderTime) }}</p>
    <p>Format: {{ project.format }}</p>
    <p>Engine: {{ project.engine }}</p>
    {% if project.status == constant('AppBundle\\Entity\\Project::STATUS_NEW') %}
    <form method="post" action="{{ path('project_queue') }}">
        <input type="hidden" name="id" value="{{ project.id }}">
        <button type="submit" class="btn btn-primary">Queue project tasks</button>
    </form>
    {% endif %}
    {% if project.status == constant('AppBundle\\Entity\\Project::STATUS_FINISHED') %}
        <a class="btn btn-primary" href="{{ path('project_download', {'id': project.id}) }}">Download result</a>
    {% endif %}
    {% if project.status != constant('AppBundle\\Entity\\Project::STATUS_NEW') %}
        <div class="table-responsive">
            <table class="table project-detail-table">
                <thead>
                    <tr>
                        <th class="col-xs-1">Frame</th>
                        <th class="col-xs-1">Status</th>
                        <th class="col-xs-1">Runtime</th>
                        <th class="col-xs-1">Remaining</th>
                        <th class="col-md-8 col-lg-8 col-sm-1 col-xs-1">Progress</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in project.tasks %}
                        {% set background = '' %}
                        {% set showImage = false %}
                        {% if task.status == constant('AppBundle\\Entity\\Task::STATUS_FINISHED') %}
                            {% set background = 'success' %}
                            {% set showImage = true %}
                        {% elseif task.status == constant('AppBundle\\Entity\\Task::STATUS_RENDERING') %}
                            {% set background = 'info' %}
                        {% endif %}
                        <tr class="{{ background }}" id="{{ task.id }}">
                            <td>{{ task.frameNumber }}</td>
                            <td>{% if showImage %}<a href="{{ path('task_image', {'id': task.id}) }}" target="_blank">{% endif %}{{ task.status }}{% if showImage %}</a>{% endif %}</td>
                            <td>{{ datetime.formatSeconds(task.runtime) }}</td>
                            <td>{{ datetime.formatSeconds(task.remaining) }}</td>
                            <td>
                                <div class="progress hidden-sm hidden-xs">
                                    <div class="progress-bar" role="progressbar" aria-valuenow="{{ (task.progress * 100)|number_format(0) }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ (task.progress * 100)|number_format(0) }}%;">
                                        {{ (task.progress * 100)|number_format(0) }}%
                                    </div>
                                </div>
                                <div class="hidden-md hidden-lg no-progress-bar">
                                    {{ (task.progress * 100)|number_format(0) }}%
                                </div>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    {% endif %}
{% endblock %}

{% block additionalJs %}
    <script>
        var statusUrl = "{{ path('project_status_ajax', {'id': project.id}) }}";
        var projectStatus = "{{ project.status }}";
        var imageUrl = "{{ path('task_image', {'id': 42}) }}";
        var downloadUrl = "{{ path('project_download', {'id': project.id}) }}";
    </script>
{% endblock %}

src/AppBundle/Resources/views/project_index.html.twig
{% extends 'AppBundle::base.html.twig' %}
{% import 'AppBundle:macros:datetime.html.twig' as datetime %}

{% block body %}
    <h1>Projects</h1>
    <p><a href="{{ path('project_add') }}" class="btn btn-primary">Add new</a></p>
    <table class="table table-striped">
        <thead>
            <tr>
                <td>Name</td>
                <td>Status</td>
                <td>Render Time</td>
                <td>Time / Frame</td>
                <td>Progress</td>
                <td>&nbsp;</td>
            </tr>
        </thead>
        <tbody>
            {% for project in projects %}
                {% set background = '' %}
                {% set showImage = false %}
                {% if project.status == constant('AppBundle\\Entity\\Project::STATUS_FINISHED') %}
                    {% set background = 'success' %}
                    {% set showImage = true %}
                {% elseif project.status == constant('AppBundle\\Entity\\Project::STATUS_RENDERING') %}
                    {% set background = 'info' %}
                {% endif %}
                <tr class="{{ background }}">
                    <td><a href="{{ path('project_detail', { id: project.id }) }}">{{ project.name }}</a></td>
                    <td>{{ project.status }}</td>
                    <td>{{ datetime.formatSeconds(project.renderTime) }}</td>
                    <td>{{ datetime.formatSeconds(project.averageFrameRenderingTime) }}</td>
                    <td>{{ (project.progress * 100)|number_format(0) }}%</td>
                    <td>
                        <a href="{{ path('project_delete', {'id': project.id}) }}">
                            <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

src/AppBundle/Resources/views/user_add_edit.html.twig
{% extends 'AppBundle::base.html.twig' %}

{% block body %}
    <h1>{% if user.id > 0 %}Edit{% else %}Add{% endif %} user</h1>
    <form method="post" enctype="multipart/form-data">

        <div class="form-group{% if errors.username is defined %} has-error{% endif %}">
            <label for="username">Username</label>
            <input type="text" class="form-control"  name="username" id="username" value="{{ user.username }}">
            {% if errors.username is defined %}<span class="help-block">{{ errors.username.message }}</span>{% endif %}
        </div>

        <div class="form-group{% if errors.password is defined %} has-error{% endif %}">
            <label for="password">Password</label>
            <input type="password" class="form-control"  name="password" id="password">
            {% if errors.password is defined %}<span class="help-block">{{ errors.password.message }}</span>{% endif %}
        </div>

        <div class="form-group{% if errors.email is defined %} has-error{% endif %}">
            <label for="email">Email</label>
            <input type="email" class="form-control"  name="email" id="email" value="{{ user.email }}">
            {% if errors.email is defined %}<span class="help-block">{{ errors.email.message }}</span>{% endif %}
        </div>

        <div class="checkbox">
            <label>
                <input type="checkbox" name="admin" value="true"{% if user.role == 'ROLE_ADMIN' %} checked{% endif %}> This user is an administrator
            </label>
        </div>

        <button type="submit" class="btn btn-primary">Save</button>
        <a href="{{ path('user_index') }}" class="btn btn-default">Cancel</a>
    </form>
{% endblock %}

src/AppBundle/Resources/views/user_index.html.twig
{% extends 'AppBundle::base.html.twig' %}
{% import "AppBundle:macros:pagination.html.twig" as pagination %}

{% block body %}
    <h1>Users</h1>
    <p><a href="{{ path('user_add') }}" class="btn btn-primary">Add new</a></p>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>Username</th>
                <th>Email</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>
                        <a href="{{ path('user_edit', {'id': user.id}) }}"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                        &nbsp;
                        <a href="{{ path('user_delete', {'id': user.id}) }}"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {{ pagination.render(pages, page, 'user_index', 'page') }}
{% endblock %}